import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import { CommonStoreProvider } from "@/store/Common";
import Header from "@/components/header";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "RohJooHoon - Portfolio",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CommonStoreProvider>
      <html lang="kr">
        <body className={poppins.className}>
          <Header />
          {children}
        </body>
      </html>
    </CommonStoreProvider>
  );
}
